### ISSUE TITLE
File previews

### ISSUE THREAD

**Issue by hut** [D630/blscd#1]
Nice project!

If you want ranger-like file previews, you could modify __blscd_build_array to use ranger's scope.sh script instead of ```file --mime-type```. It does a pretty good job at generating them automatically, depending on file path and the size of the drawing area: https://github.com/hut/ranger/blob/master/ranger/data/scope.sh

Although it would kill the performance even further :D  But it all scales in hardware, right?

**Comment by D630** [comment]
Hey, I just released version 0.2.0, a faster and stripped-down version. I consider this issue as closed, because I am not gonna add big functionalities to blscd in the future. Bash is a bit too slow for my taste here; associative arrays can be very handy, but in this case also very annoying. Maybe I will rewrite it in ksh shell as klscd...

Mabye.
